### PR TITLE
Update ReadMe

### PR DESCRIPTION
**Pull request by renniepak**
Added Docker MacOs command. --net host only seems to work for Linux?

### CODE REVIEW

**Comment by mablanco** [comment]
Hi there. I don't have a Mac so I cannot test your contribution. Are you sure you're able to authenticate against the Web UI if you don't include the "--net host" parameter? Thx.

**Comment by renniepak** [comment]
Yes I'm positive. Adding the -p 5000:5000 makes sure however that I can connect to localhost:5000 on host os.
________________________________

**Comment by mablanco** [comment]
Besides connecting to port 5000, are you also able to authenticate against the Web UI using the password in the config file? I mean, I can also connect to port 5000 without the "--net host" parameter, but I'm unable to authenticate in Linux without it. I just want to make sure we're talking about the same thing.

**Comment by renniepak** [comment]
Yes. I’m positive. Have used it exactly like that. Unfortunaly not in the position to re-check atm.

________________________________
Van: Marco Antonio Blanco <notifications@github.com>
Verzonden: Wednesday, July 31, 2019 7:42:17 PM
Aan: mablanco/docker-osmedeus <docker-osmedeus@noreply.github.com>
CC: renniepak <>; Author <author@noreply.github.com>
Onderwerp: Re: [mablanco/docker-osmedeus] Update ReadMe (#4)


Besides connecting to port 5000, are you also able to authenticate against the Web UI using the password in the config file? I mean, I can also connect to port 5000 without the "--net host" parameter, but I'm unable to authenticate in Linux without it. I just want to make sure we're talking about the same thing.

**Comment by mablanco** [comment]
Ok, merge done. Thx for the contribution.

**Pull request merged**
